global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "supatable-api-docker"
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8080"]

  - job_name: "supatable-api-rider"
    metrics_path: /metrics
    static_configs:
      - targets: ["host.docker.internal:5000"]
